### ISSUE TITLE
Things ToDo

### ISSUE THREAD

**Issue by gustavoLuuD** [gustavoLuuD/What-I-did-in-college#1]
- [ ] Create the 2nd semester branch
- [ ] Post another project for the 1st semester 
- [ ] Translate this project to portuguese :)
